name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # ✅ Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'  # ✅ Go 1.22 o superior

      - name: Build
        run: |
          mkdir -p bin
          go build -v -o bin/app .
          cp -r templates bin/

      - name: Test
        run: go test -v ./...

      - name: Package artifact
        run: |
          cd bin
          zip -r ../app.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app.zip
